### ISSUE TITLE
Does this work using the text,extdb spring profile?

### ISSUE THREAD

**Issue by leonj1** [arnaldop/enhanced-pet-clinic#1]
Upon using that spring config, running the unmodified sql files that came with the project I get the below error.

Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select username,authority from authorities where username = ?]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'field list'

Here is the current schema for table authorities:
id  bigint(20)  NO  PRI NULL    auto_increment
authority   varchar(255)    NO      NULL    

I could create a 'username' field, but that seems wrong here.
Honestly I dont know where this is coming from and therefore not sure where to check to fix it.

**Comment by arnaldop** [comment]
I just committed some changes. Note the "live" profile has been renamed to "secure" and a new "live" profile has beed added, which does not initialize the database. This is probably not the best way to do it in a real application, but it demonstrates the options in this sample application.
