### ISSUE TITLE
Is this project functional?

### ISSUE THREAD

**Issue by jrmillerwork** [arnaldop/enhanced-pet-clinic#2]
Getting traceback with this message:
 PreparedStatementCallback; bad SQL grammar [select username,authority from authorities where username = ?]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'username' in 'field list'

Is this a known problem?

I should mention that I tried to change the project to use a mysql database instead of in-memory db.
trying changing mysql table definition.

Adding username to authorities table fixed issue.

**Comment by arnaldop** [comment]
It shouldn't be, but I'll check this weekend and let you know.
Thanks!

**Comment by jrmillerwork** [comment]
Key point was changing over to the mysql DB. As I mentioned in later edits,
I managed to get the error to go away by adding username to authorities
table. But I can't get new users that i have created to log in.

**Comment by arnaldop** [comment]
The last few commits have made the project runnable as is.
