### ISSUE TITLE
log cannot be resolved

### ISSUE THREAD

**Issue by ghost** [arnaldop/enhanced-pet-clinic#3]
HI!
I have forked the enhanced-pet-clinic project. Then I imported the project in STS environment based on Eclipse Neon. STS in throwing the following error: 

`log  cannot be resolved` on every line where the `log ` object is used like so : 

`log.info("(beforeExceptionHandler) Before executing '" + jp.getSignature().toLongString() + "'");`

At the state of the last commit (934b2599939f1fa0e533b62d1a2fed64a0541028) on March 31, 2016 the project is using project lombok version 1.16.8.

**Comment by arnaldop** [comment]
Do you have Lombok enabled in Eclipse?
If you can run `mvn compile` and everything compiles fine, then it's an IDE issue, and it's probably Lombok.

**Comment by ghost** [comment]
Please can you show me how to enable lombok on Spring Tool Suite.

**Comment by arnaldop** [comment]
1. Go to https://projectlombok.org/
2. Download JAR file.
3. Run JAR file. Usually double-clicking JAR file is enough.
4. In the Lombok installation screen, make sure that your Spring Tool Suite instance is listed.
5. Click Install/Update, then Quit Installer.
6. Open Spring Tool Suite, go to About Spring Tool Suite. The large area that contains the version number should have the Lombok version listed at the bottom. You might have to scroll, even though there is no scroll bar.

All done.

**Comment by TuringTD** [comment]
how to do??
@ElomSkillupsoft

**Comment by arnaldop** [comment]
@TuringTD, how to do what?
I gave detailed instructions on how to solve the problem in this ticket.
What additional information are you looking for?

**Comment by TuringTD** [comment]
“log”  displays red error in  my IDEA

**Comment by arnaldop** [comment]
Here are the installation instructions for Project Lombok on IntelliJ: https://projectlombok.org/setup/intellij

**Comment by niranjantdesai** [comment]
If STS shows an error even after enabling Lombok, try cleaning the project and building again.

**Comment by basilgafoor** [comment]
It may be related to @Slf4j and may be you are using any latest version of project lombok (1.18.x)+
try to install the earlier versions like 1.16.x which supports @Slf4j.

And then restart eclipse and rebuilt the project.

**Comment by PoojithaReddyPalwai** [comment]
I have faced the same issue .I just configured lombok again and it worked !!

Followed this tutorial to do the same : https://www.youtube.com/watch?v=5j2hr8l9F7Y
